name: Pull Request
on: pull_request

jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      # checkout branch
      - name: Checkout
        uses: actions/checkout@v2

      # setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # install deps
      - name: Install dependencies
        run: npm ci

      # run tests
      - name: Run tests
        run: npm run test

      # build lib
      - name: Build library
        run: npm run build
