name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Library Release
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      # checkout branch
      - name: Checkout
        uses: actions/checkout@v1

      # setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # install deps
      - name: Install dependencies
        run: npm ci

      # build lib
      - name: Build library
        run: npm run build

      # run tests
      - name: Run tests
        run: npm run test

      # release new version
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
